services:
  api:
    image: api:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uv run uvicorn api.main:app --host 0.0.0.0 --port 8000
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      - minio

  minio:
    image: minio/minio
    ports:
      - "9020:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data

  postgres:
    image: postgres:15
    ports:
      - "7432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nyc_taxi
