version: '3'
env:
  KEEP_CONTAINERS: "false"

tasks:
  test:
    cmds:
      - docker compose -f docker-compose.yaml up minio postgres -d
      - uv run pytest -svv --maxfail=1
      - defer: if [ "$KEEP_CONTAINERS" = "false" ]; then docker compose -f docker-compose.yaml down -v --remove-orphans; else echo "Containers are being kept"; fi

  build:
    cmds:
      - docker build -t api:latest .

  download:testdata:
    cmds:
      - python download.py 2025

  lint:
    cmds:
      - uv run ruff check --fix .

  format:
    cmds:
      - uv run ruff format .
